# Generated by Django 3.1.7 on 2021-04-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210330_0439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-fav_counter', '-pub_date')},
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название тега для HTML'),
        ),
    ]
