# Generated by Django 3.1.7 on 2021-05-07 05:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('amount', models.DecimalField(
                    decimal_places=1,
                    max_digits=6,
                    validators=[django.core.validators.MinValueValidator(1)]
                )),
            ],
            options={
                'verbose_name_plural': 'Состав',
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    db_index=True,
                    help_text='Название ингредиента, максимум 100 символов',
                    max_length=100,
                    unique=True,
                    verbose_name='Название ингредиента'
                )),
                ('unit', models.CharField(
                    help_text='Единица измерения, максимум 20 симоволов',
                    max_length=20,
                    verbose_name='Единица измерения'
                )),
            ],
            options={
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    help_text='Тег рецепта, максимум 20 символов',
                    max_length=20,
                    verbose_name='Тег'
                )),
                ('display_name', models.CharField(
                    blank=True,
                    max_length=50,
                    verbose_name='Название тега для HTML'
                )),
                ('color', models.CharField(
                    blank=True,
                    max_length=20,
                    verbose_name='Цвет тега'
                )),
            ],
            options={
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    help_text='Максимальная длинна 100 символов',
                    max_length=100, verbose_name='Название рецепта'
                )),
                ('image', models.ImageField(
                    help_text='Изображение',
                    upload_to='recipes/',
                    verbose_name='Изображение'
                )),
                ('description', models.TextField(
                    blank=True,
                    help_text='Описание рецепта',
                    verbose_name='Описание'
                )),
                ('time_cooking', models.PositiveSmallIntegerField(
                    verbose_name='Вермя приготовления'
                )),
                ('pub_date', models.DateTimeField(
                    auto_now_add=True,
                    help_text='Дата публикации',
                    verbose_name='Дата публикации'
                )),
                ('fav_counter', models.PositiveSmallIntegerField(
                    default=0,
                    help_text='Количество добавлений в избранное',
                    verbose_name='Добавление в избранное'
                )),
                ('slug', models.SlugField(
                    blank=True,
                    max_length=500,
                    unique=True
                )),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='recipes',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор'
                )),
                ('ingredients', models.ManyToManyField(
                    help_text='Игредиенты',
                    through='recipes.Amount',
                    to='recipes.Composition',
                    verbose_name='Игредиенты'
                )),
                ('tags', models.ManyToManyField(
                    help_text='Тег рецепта',
                    to='recipes.Tag',
                    verbose_name='Теги'
                )),
            ],
            options={
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='following',
                    to=settings.AUTH_USER_MODEL
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='follower',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name_plural': 'Подписка',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('recipe', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='favorite',
                    to='recipes.recipe'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='favorites',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='purchases',
                    to=settings.AUTH_USER_MODEL
                )),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='recipes.recipe'
                )),
            ],
            options={
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.AddField(
            model_name='amount',
            name='ingredient',
            field=models.ForeignKey(
                help_text='Ингредиент',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='recipes.composition',
                verbose_name='Ингредиент'
            ),
        ),
        migrations.AddField(
            model_name='amount',
            name='recipe',
            field=models.ForeignKey(
                help_text='Рецепт',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipe_ingredients',
                to='recipes.recipe',
                verbose_name='Рецепт'
            ),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_subscription'
            ),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(
                fields=('item', 'customer'),
                name='unique_purchase'
            ),
        ),
    ]
