# Generated by Django 3.1.7 on 2021-03-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цвет тега'),
        ),
    ]
